### ISSUE TITLE
Tag #bin_color#

### ISSUE THREAD

**Issue by ashkii7** [hugoKs3/plugin-mybin#43]
Hello,
When I use the # bin_color # tag in the title or body of a notification action message, its value is in English instead of being for example in French.
Could we not that this value appears in the right language that is to say depending on the language configured in Jeedom?
cordially
ashkii7

**Comment by hugoKs3** [comment]
Hello,
Actually, the value of the tag is the "id" of the bin type/color, not its name.
I code in "english" so ids are in english.

**Comment by ashkii7** [comment]
Hello,
Thank you for your reply.
Ok for the ID, I can understand this mode of management (which is independent on the language used) so when you use the "bin_color" tag in a message you use this ID to translate it into "text", so actually, by default with the English value of the text.
But then what prevents you from going to get before the current language of the Jeedom core and then translate this "text" into the right language?
The current problem arises for me in French but is also valid for a German or a Russian.
It's still a pity not to adapt the code accordingly, right?

Another question: what is the interest of having a counter on the bins that have been released / picked up? I do not understand the approach, because once they have been out / picked up, personally I do not care how many times have been since for example the beginning of the year for example. It's bizarre this counter. For me, it is useless, but it's just my opinion.
cordially
PS : Google Translation is my friend
ashkii7

**Comment by hugoKs3** [comment]
Hello, 
Yes, I could have done this in a better way... If I change now, it would impact users already using this tag.
As for the counter, some people (for specific bins like the plants) are only allowed for a specific number of collect per year. The counter helps them to know where they stand and prevent any notification once the threshold reached.
