### ISSUE TITLE
Occurrences d'un jour sur le mois 

### ISSUE THREAD

**Issue by kabalagi** [hugoKs3/plugin-mybin#46]
Bonjour,

j'ai eu besoin de positionner des cycles basés sur des occurrences : premier et troisième lundi du mois ou encore dernier vendredi du mois. Pour cela, j'ai modifié votre plugin sur mon installation. Je ne suis pas habitué à faire des pull-request sur github, aussi je me permet de vous envoyer mes modifs. Peut-être que vous pourrez vous en inspirer si la fonctionnalité décrite est de nature à intéresser d'autres utilisateurs (désolé pour le format de la demande) : 

Ajouts dans mybin.php : 

<div class="form-group">
 <label class="col-sm-3 control-label">{{Occurrence(s) du mois}}</label>
 <div class="col-sm-7">
  <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_0" />{{Tous}}</label>
 <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_1" />{{1er du mois}}</label>
 <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_2" />{{2Ã¨me}}</label>
 <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_3" />{{3Ã¨me}}</label>
 <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_4" />{{4Ã¨me}}</label>
 <label class="checkbox-inline"><input type="checkbox" class="eqLogicAttr" data-l1key="configuration" data-l2key="Occm_5" />{{Dernier du mois}}</label>
 </div>
</div>

Ajouts dans mybin.class.php : 

fonction preInsert()
...
            $this->setConfiguration('Occm_0', 1);
...

fonction checkIfBin : 
...
        $year = 1 * $dt->format('Y');
        if ($this->getConfiguration('Occm_0') == 1) {
           $isocc = true;
        } else {
           if ($isday) {
              $dayj = 1 * $dt->format('j');
              $dtTemp = new DateTime($year . '-' . $month . '-01');
              $Occdate = 0;
              for ($i = 1; $i <= $dayj; $i++) {
                 $daysem = 1 * $dtTemp->format('w');
                 if ($daysem == $day) {
                    $Occdate++;
                 }
                 $dtTemp->modify('+1 day');
              }
              if ($Occdate >= 1 && $Occdate <= 4) {
                 if ($this->getConfiguration('Occm_'.$Occdate) == 1) {
                    $isocc = true;
                 }
              }
              $dtTemp->modify('+6 day');
              $moisCheck = 1 * $dtTemp->format('n');
              if ($moisCheck != $month && $this->getConfiguration('Occm_5') == 1) {
                 $isocc = true;
              }
           }
        }

        if ($isSpecificCron || $isSpecificDay || ($isMonth && $isweek && $isday && $isocc)) {
...

fonction getNextCollectsAndNotifs : 
...
            $year = 1 * $dtCheck->format('Y');
            $occOK = false;
            if ($this->getConfiguration('Occm_0') == 1) {
               $occOK = true;
            } else {
               if ($this->getConfiguration('day_'.$day) == 1) {
                  $dayj = 1 * $dtCheck->format('j');
                  $dtTemp = new DateTime($year . '-' . $month . '-01');
                  $Occdate = 0;
                  for ($cpt = 1; $cpt <= $dayj; $cpt++) {
                     $daysem = 1 * $dtTemp->format('w');
                     if ($daysem == $day) {
                        $Occdate++;
                     }
                     $dtTemp->modify('+1 day');
                  }
                  if ($Occdate >= 1 && $Occdate <= 4) {
                     if ($this->getConfiguration('Occm_'.$Occdate) == 1) {
                        $occOK = true;
                     }
                  }
                  $dtTemp->modify('+6 day');
                  $moisCheck = 1 * $dtTemp->format('n');
                  if ($moisCheck != $month && $this->getConfiguration('Occm_5') == 1) {
                     $occOK = true;
                  }
               }
            }
            if ($this->getConfiguration('month_'.$month) == 1 && (($week%2 == 0 && $this->getConfiguration('paire') == 1) || ($week%2 != 0 && $this->getConfiguration('impaire') == 1)) && $this->getConfiguration('day_'.$day) == 1 && $occOK) {
...

**Comment by kabalagi** [comment]
Bon, le plus simple est encore de vous donner les deux fichiers modifiés. Les modifs apparaissent entre deux commentaires /* MODIF GK*/ et /* FIN MODIF GK */
[mybin.class.txt](https://github.com/hugoKs3/plugin-mybin/files/6478908/mybin.class.txt)
[mybin.txt](https://github.com/hugoKs3/plugin-mybin/files/6478909/mybin.txt)

**Comment by hugoKs3** [comment]
Contribution intégrée dans la branche DEV
